# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet16-small-pgd-at2
# name: xx/
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 10

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /131_data/datasets/sidd/train/gt_crops.lmdb
    dataroot_lq: /131_data/datasets/sidd/train/input_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: /131_data/datasets/sidd/SIDD/val/gt_crops.lmdb
    dataroot_lq: /131_data/datasets/sidd/SIDD/val/input_crops.lmdb
    io_backend:
      type: lmdb


network_g:
  type: NAFNet
  width: 16
  enc_blk_nums: [2, 2, 2, 2]
  middle_blk_num: 2
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ~
  # pretrain_network_g: /131_data/dhryou/NAFNet/experiments/NAFNet-SIDD-width16-15-train-0-55-filter/models/net_g_3000.pth
  # pretrain_network_g: /131_data/dhryou/NAFNet/experiments/NAFNet-SIDD-width16-5-to-25-filter/models/net_g_60000.pth
  strict_load_g: false
  resume_state: ~
  root: '/131_data/dhryou/NAFNet'
  # root: '/Frequency_Filtering'

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  optim_g2:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 25000
  warmup_iter: -1 # no warm ups

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

  adv: true
  alpha: 0.5
  filter: false
  filter_rate : 0.3

# validation settings
val:
  val_freq: 2000
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: 5000
  use_tb_logger: false
  wandb:
    # project: test-project
    project: Robust
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
