# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet64-finetuning-pgd-16
# name: xxx
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 10

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /131_data/datasets/sidd/train/gt_crops.lmdb
    dataroot_lq: /131_data/datasets/sidd/train/input_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: /131_data/datasets/sidd/SIDD/val/gt_crops.lmdb
    dataroot_lq: /131_data/datasets/sidd/SIDD/val/input_crops.lmdb
    io_backend:
      type: lmdb


network_g:
  type: NAFNet
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ./finetuned_models/NAFNet-SIDD-width64.pth
  # advtrained_network_g: /131_data/dhryou/NAFNet/experiments/NAFNet-width64-adversarial-training/models/
  # pretrain_network_g: /131_data/dhryou/NAFNet/experiments/NAFNet-width64-adversarial-training/models/
  # pretrain_network_g: ./finetuned_models/NAFNet-weight64-advtrained.pth
  # pretrain_network_g: ./finetuned_models/adv-training.pth
  # pretrain_network_g: ./finetuned_models/adv-training.pth
  # pretrain_network_g: ./finetuned_models/net_g_300000.pth
  # pretrain_network_g: ~
  # strict_load_g: true
  strict_load_g: true
  resume_state: ~
  root: '/131_data/dhryou/FF'

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 25000
    eta_min: !!float 1e-6

  total_iter: 25000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

  adv: true
  alpha: 0.5
  filter: false
  filter_rate : 0.3
  fq_aug : false
  feature : false
  fbr_param : 0.5
  fbr_mode : 'linear'

  perturb:
    alpha: 16
    iter: 1

# validation settings
val:
  val_freq: !!float 2e3
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: NAFNet-generalization
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
